version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - ./src:/app
    ports:
      - 8000:8000
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/movies
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
